UIWeb/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace UIWeb.Areas.Admin.Controllers
{
  [Area("Admin")] // Controller için area belirteci
  [Authorize(Roles = "Admin, Editor")]

  public class DashboardController : Controller
  {
    // Views
    public IActionResult Index()
    {
      TempData["primary"] = $"{DateTime.Now.ToShortDateString()} | {DateTime.Now.ToShortTimeString()}";
      return View();
    }
  }
}

UIWeb/Components/PostSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;

namespace UIWeb.Components
{
  public class PostSummaryViewComponent : ViewComponent
  {
    // DI
    private readonly IServiceManager _manager;

    // Constructor
    public PostSummaryViewComponent(IServiceManager manager)
    {
      _manager = manager;
    }

    // ViewComponent
    public string Invoke() // Gönderi sayısı döner.
    {
      return _manager.PostService.GetAllPosts(false).Count().ToString();
    }
  }
}

UIWeb/Controllers/PostController.cs
using System.Security.Claims;
using Core.Dtos;
using Core.Models;
using Core.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Service.UnitOfWork;
using UIWeb.Models;

namespace UIWeb.Controllers
{
  public class PostController : Controller
  {
    //Dependency Injection
    private readonly IServiceManager _manager;

    // Constructor
    public PostController(IServiceManager manager)
    {
      _manager = manager;
    }

    // SelectList
    private SelectList GetCategories()
    {
      return new SelectList(_manager.CategoryService.GetAllCategories(false), "Id", "Name", "1");
    }

    // Views
    public IActionResult Index(PostRequestParameters p)
    {
      var posts = _manager.PostService.GetAllPostsWithDetails(p).OrderByDescending(p => p.CreatedAt);
      var pagination = new Pagination()
      {
        CurrentPage = p.PageNumber,
        ItemsPerPage = p.PageSize,
        TotalItems = _manager.PostService.GetAllPosts(false).Count()
      };
      return View(new PostListViewModel()
      {
        Posts = posts,
        Pagination = pagination
      });
    }

    public IActionResult Get([FromRoute(Name = "id")] int id)
    {
      var model = _manager.PostService.GetOnePost(id, false);
      return View(model);
    }

    public IActionResult Create()
    {
      ViewBag.Categories = GetCategories();
      return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] PostDtoForCreation postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();
      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);
        postDto.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        _manager.PostService.CreateOnePost(postDto);
        TempData["success"] = $"{postDto.Title} oluşturuldu.";
        return RedirectToAction("Index");
      }
      return View();
    }

    public IActionResult Update([FromRoute(Name = "id")] int id)
    {
      ViewBag.Categories = GetCategories();
      var model = _manager.PostService.GetOnePostForUpdate(id, false);
      return View(model);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update([FromForm] PostDtoForUpdate postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();

      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);

        _manager.PostService.UpdateOnePost(postDto);
        return RedirectToAction("Index");
      }
      return View(postDto);
    }

    public IActionResult Delete(int id)
    {
      _manager.PostService.DeleteOnePost(id);
      TempData["danger"] = "Gönderi silindi!";
      return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddComment([FromForm] CommentDto commentDto)
    {
      if (ModelState.IsValid)
      {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        commentDto.UserId = userId;
        _manager.CommentService.CreateComment(commentDto);
        return RedirectToAction("Get", new { id = commentDto.PostId });
      }
      return View("Get", _manager.PostService.GetOnePost(commentDto.PostId, false));
    }
    [HttpPost("Post/{postId}/RemoveComment")]
    [ValidateAntiForgeryToken]
    public IActionResult RemoveComment([FromRoute] int postId, [FromForm] int commentId)
    {
      _manager.CommentService.RemoveComment(commentId);
      return RedirectToAction("Get", new { id = postId });
    }

    [HttpPost("Post/{postId}/ToggleLike")]
    [ValidateAntiForgeryToken]
    public IActionResult ToggleLike([FromRoute] int postId)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      if (string.IsNullOrEmpty(userId))
        return Unauthorized();
      _manager.LikeService.ToggleLike(postId, userId);
      return RedirectToAction("Get", new { id = postId });
    }
  }
}

UIWeb/Views/Shared/_Footer.cshtml
<div class="container border-top">
  <footer class="py-3 mb-3">
    <ul class="nav justify-content-center mb-3">
      <li class="nav-item"><a asp-page="/About" class="nav-link px-2 text-body-secondary">Proje Hakkında</a></li>
      <li class="nav-item"><a asp-page="/Contact" class="nav-link px-2 text-body-secondary">İletişim</a></li>
    </ul>
    <p class="text-center text-body-secondary">BilgeAdam Akademi | Recep Ersin Uluağaç</p>
  </footer>
</div>

UIWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
  @RenderSection("Styles", false)
</head>

<body>
  <header>
    <partial name="_Navbar" />
    <partial name="_Notification" class="row text-end my-2" />
    @RenderSection("Header", false)
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>
  <footer class="container">
    @RenderSection("Footer", false)
    <partial name="_Footer" />
  </footer>
  <script src="~/lib/jquery/jquery.min.js"></script>
  <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/lib/font-awesome/js/all.min.js"></script>
  @RenderSection("Scripts", false)
</body>

</html>

UIWeb/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <i class="fa-solid fa-house"></i> NetBlog
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-lg-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
            Ana Sayfa
          </a>
        </li>
        @if (User.Identity.IsAuthenticated)
        {
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" aria-current="page" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Gönderiler
            </a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" asp-controller="Post" asp-action="Index">
                  Gönderiler (@await Component.InvokeAsync("PostSummary"))
                </a>
              </li>

              <li>
                <a class="dropdown-item" asp-controller="Post" asp-action="Create">
                  Gönderi Oluştur
                </a>
              </li>

            </ul>
          </li>
        }
        else
        {
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" asp-controller="Post" asp-action="Index">
              Gönderiler (@await Component.InvokeAsync("PostSummary"))
            </a>
          </li>
        }
      </ul>
      <ul class="navbar-nav">

        <partial name="_SignMenu" />
      </ul>
    </div>
  </div>
</nav>

UIWeb/Views/Shared/_Notification.cshtml
@if (TempData["primary"] is not null)
{
  <div class="alert alert-primary" role="alert">
    @TempData["primary"]
  </div>
}

@if (TempData["success"] is not null)
{
  <div class="alert alert-success" role="alert">
    @TempData["success"]
  </div>
}

@if (TempData["danger"] is not null)
{
  <div class="alert alert-danger" role="alert">
    @TempData["danger"]
  </div>
}

UIWeb/Views/Shared/_SignMenu.cshtml
@if (User.Identity.IsAuthenticated)
{
  @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
  {
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" target="_blank" asp-area="Admin" asp-controller="Dashboard"
        asp-action="Index">
        <i class="fa-solid fa-gears"></i> Panel
      </a>
    </li>
  }
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle active" aria-current="page" role="button" data-bs-toggle="dropdown"
      aria-expanded="false">
      Profil
    </a>
    <ul class="dropdown-menu">
      <li>
        <a asp-controller="Account" asp-action="Profile" class="dropdown-item">
          <i class="fa-solid fa-user mx-2"></i>Profilim
        </a>
      </li>
      <li>
        <a class="dropdown-item" asp-controller="Account" asp-action="SignOut">
          <i class="fa-solid fa-right-from-bracket mx-2"></i>Çıkış
        </a>
      </li>
    </ul>
  </li>
}
else
{
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-controller="Account" asp-action="SignIn"
      asp-route-returnUrl="@Context.Request.Path">
      <i class="fa-solid fa-user"></i> Giriş
    </a>
  </li>
}