UIWeb/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;
using UIWeb.Areas.Admin.Models;

namespace UIWeb.Areas.Admin.Controllers
{
  [Area("Admin")] // Controller için area belirteci
  [Authorize(Roles = "Admin, Editor")]
  public class CategoryController : Controller
  {
    private readonly IServiceManager _manager;

    public CategoryController(IServiceManager manager)
    {
      _manager = manager;
    }

    // Views
    public IActionResult Index()
    {
      return View(_manager.CategoryService.GetAllCategories(false));
    }

    public IActionResult Create()
    {
      var model = new CategoryCreateViewModel
      {
        Categories = _manager.CategoryService.GetAllCategories(false)
      };
      return View(model);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(CategoryCreateViewModel model)
    {
      if (ModelState.IsValid)
      {
        _manager.CategoryService.AddCategory(model.NewCategory);
      }
      return RedirectToAction("Index");
    }
  }
}

UIWeb/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;

namespace UIWeb.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize(Roles = "Admin")]

  public class RoleController : Controller
  {
    private readonly IServiceManager _manager;

    public RoleController(IServiceManager manager)
    {
      _manager = manager;
    }

    public IActionResult Index()
    {
      return View(_manager.AuthService.Roles);
    }
  }
}

UIWeb/Areas/Admin/Controllers/UserController.cs
using Core.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service.UnitOfWork;

namespace UIWeb.Areas.Admin.Controllers
{
  [Area("Admin")]
  [Authorize(Roles = "Admin")]

  public class UserController : Controller
  {
    private readonly IServiceManager _manager;

    public UserController(IServiceManager manager)
    {
      _manager = manager;
    }

    public SelectList GetAllRoles()
    {
      return new SelectList(_manager.AuthService.Roles);
    }
    public async Task<IActionResult> Index()
    {
      ViewBag.Roles = GetAllRoles();
      return View(await _manager.AuthService.GetAllUsersWithRole());
    }

    public async Task<IActionResult> Update([FromRoute(Name = "id")] string id)
    {
      var user = await _manager.AuthService.GetOneUserForUpdate(id);
      return View(user);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update([FromForm] UserDtoForUpdate userDto)
    {
      if (ModelState.IsValid)
      {
        await _manager.AuthService.Update(userDto);
        return RedirectToAction("Index");
      }
      return View();
    }
  }
}

UIWeb/Controllers/PostController.cs
using System.Security.Claims;
using Core.Dtos;
using Core.Models;
using Core.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Service.UnitOfWork;
using UIWeb.Models;

namespace UIWeb.Controllers
{
  public class PostController : Controller
  {
    //Dependency Injection
    private readonly IServiceManager _manager;

    // Constructor
    public PostController(IServiceManager manager)
    {
      _manager = manager;
    }

    // SelectList
    private SelectList GetCategories()
    {
      return new SelectList(_manager.CategoryService.GetAllCategories(false), "Id", "Name", "1");
    }

    // Views
    public IActionResult Index(PostRequestParameters p)
    {
      var posts = _manager.PostService.GetAllPostsWithDetails(p).OrderByDescending(p => p.CreatedAt);
      var pagination = new Pagination()
      {
        CurrentPage = p.PageNumber,
        ItemsPerPage = p.PageSize,
        TotalItems = _manager.PostService.GetAllPosts(false).Count()
      };
      return View(new PostListViewModel()
      {
        Posts = posts,
        Pagination = pagination
      });
    }

    public IActionResult Get([FromRoute(Name = "id")] int id)
    {
      var model = _manager.PostService.GetOnePost(id, false);
      return View(model);
    }

    public IActionResult Create()
    {
      ViewBag.Categories = GetCategories();
      return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] PostDtoForCreation postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();
      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);
        postDto.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        _manager.PostService.CreateOnePost(postDto);
        TempData["success"] = $"{postDto.Title} oluşturuldu.";
        return RedirectToAction("Index");
      }
      return View();
    }

    public IActionResult Update([FromRoute(Name = "id")] int id)
    {
      ViewBag.Categories = GetCategories();
      var model = _manager.PostService.GetOnePostForUpdate(id, false);
      return View(model);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update([FromForm] PostDtoForUpdate postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();

      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);

        _manager.PostService.UpdateOnePost(postDto);
        return RedirectToAction("Index");
      }
      return View(postDto);
    }

    public IActionResult Delete(int id)
    {
      _manager.PostService.DeleteOnePost(id);
      TempData["danger"] = "Gönderi silindi!";
      return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddComment([FromForm] CommentDto commentDto)
    {
      if (ModelState.IsValid)
      {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        commentDto.UserId = userId;
        _manager.CommentService.CreateComment(commentDto);
        return RedirectToAction("Get", new { id = commentDto.PostId });
      }
      return View("Get", _manager.PostService.GetOnePost(commentDto.PostId, false));
    }
    [HttpPost("Post/{postId}/RemoveComment")]
    [ValidateAntiForgeryToken]
    public IActionResult RemoveComment([FromRoute] int postId, [FromForm] int commentId)
    {
      _manager.CommentService.RemoveComment(commentId);
      return RedirectToAction("Get", new { id = postId });
    }

    [HttpPost("Post/{postId}/ToggleLike")]
    [ValidateAntiForgeryToken]
    public IActionResult ToggleLike([FromRoute] int postId)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      if (string.IsNullOrEmpty(userId))
        return Unauthorized();
      _manager.LikeService.ToggleLike(postId, userId);
      return RedirectToAction("Get", new { id = postId });
    }
  }
}

UIWeb/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>

<body>
  <header>
    <partial name="_Navbar" />
    @RenderSection("Header", false)
  </header>
  <div class="container">
    <div class="text-center col-2">
      <partial name="_Notification" />
    </div>
    <main role="main" class="pb-3 offset-lg-3">
      @RenderBody()
    </main>
  </div>
  <footer class="offset-lg-3">
    @RenderSection("Footer", false)
    <partial name="_Footer" />
  </footer>
  <script src="~/lib/jquery/jquery.min.js"></script>
  <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/lib/font-awesome/js/all.min.js"></script>
  @await RenderSectionAsync("Scripts", false)
</body>

</html>

UIWeb/Areas/Admin/Views/Shared/_Navbar.cshtml
<!-- Buton -->
<button class="btn btn-dark d-lg-none m-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#mobileSidebar">
  <i class="fa-solid fa-bars"></i>
</button>

<!-- Büyük Ekran  -->
<div class="d-none d-lg-flex flex-column justify-content-between bg-dark text-white vh-100 position-fixed p-3"
  style="width: 250px;">
  <div>
    <h4 class="mb-4"><i class="fa-solid fa-shield mx-2"></i>Terminal</h4>
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Dashboard" asp-action="Index">
          <i class="fa-solid fa-chart-line mx-2"></i>Dashboard</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Category" asp-action="Index">
          <i class="fa-solid fa-list mx-2"></i>Kategoriler</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Post" asp-action="Index">
          <i class="fa-solid fa-file mx-2"></i>Gönderiler</a>
      </li>
      @if (User.IsInRole("Admin"))
      {
        <li class="nav-item mb-2">
          <a class="nav-link text-white" asp-controller="Role" asp-action="Index">
            <i class="fa-solid fa-users-rectangle mx-2"></i>Roller</a>
        </li>
        <li class="nav-item mb-2">
          <a class="nav-link text-white" asp-controller="User" asp-action="Index">
            <i class="fa-solid fa-users mx-2"></i>Kullanıcılar</a>
        </li>
      }
    </ul>
  </div>
  <div>
    <a class="nav-link text-white my-2" asp-area="" asp-controller="Home" asp-action="Index" target="_blank">
      <i class="fa-solid fa-home mx-2"></i>NetBlog
    </a>
    <a class="nav-link text-white my-2" asp-area="" asp-controller="Account" asp-action="SignOut">
      <i class="fa-solid fa-right-from-bracket mx-2"></i>Çıkış
    </a>
  </div>
</div>

<!-- Küçük Ekran -->
<div class="offcanvas offcanvas-start bg-dark text-white" tabindex="-1" id="mobileSidebar">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title"><i class="fa-solid fa-shield mx-2"></i>Terminal</h5>
    <button type="button" class="btn-close text-reset bg-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="nav flex-column">
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Dashboard" asp-action="Index">
          <i class="fa-solid fa-chart-line mx-2"></i>Dashboard</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Post" asp-action="Index">
          <i class="fa-solid fa-list mx-2"></i>Kategoriler</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Post" asp-action="Index">
          <i class="fa-solid fa-comments mx-2"></i>Gönderiler</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="Role" asp-action="Index">
          <i class="fa-solid fa-users-rectangle mx-2"></i>Roller</a>
      </li>
      <li class="nav-item mb-2">
        <a class="nav-link text-white" asp-controller="User" asp-action="Index">
          <i class="fa-solid fa-users mx-2"></i>Kullanıcılar</a>
      </li>
    </ul>
    <hr class="bg-light">
    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index" target="_blank">
      <i class="fa-solid fa-home mx-2"></i>NetBlog</a>
    <a class="nav-link text-white my-2" asp-area="" asp-controller="Account" asp-action="SignOut">
      <i class="fa-solid fa-right-from-bracket mx-2"></i>Çıkış
    </a>
  </div>
</div>