UIWeb/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace UIWeb.Areas.Admin.Controllers
{
  [Area("Admin")] // Controller için area belirteci
  [Authorize(Roles = "Admin, Editor")]

  public class DashboardController : Controller
  {
    // Views
    public IActionResult Index()
    {
      TempData["primary"] = $"{DateTime.Now.ToShortDateString()} | {DateTime.Now.ToShortTimeString()}";
      return View();
    }
  }
}

UIWeb/Components/AllLikeSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;

namespace UIWeb.Components
{
  public class AllLikeSummaryViewComponent : ViewComponent
  {
    // DI
    private readonly IServiceManager _manager;

    // Constructor
    public AllLikeSummaryViewComponent(IServiceManager manager)
    {
      _manager = manager;
    }

    // ViewComponent
    public async Task<string> InvokeAsync(int postId)
    {
      return _manager.LikeService.GetAllLikesCount();
    }

  }
}

UIWeb/Components/MemberSummaryViewComponent.cs
using Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;

namespace UIWeb.Components
{
  public class MemberSummaryViewComponent : ViewComponent
  {
    private readonly IServiceManager _manager;
    private readonly UserManager<ApplicationUser> _userManager;

    public MemberSummaryViewComponent(IServiceManager manager, UserManager<ApplicationUser> userManager)
    {
      _manager = manager;
      _userManager = userManager;
    }

    public async Task<string> InvokeAsync(int postId)
    {
      return _userManager.Users.Count().ToString();
      // return _manager.PostService.GetAllPosts(false).Count().ToString();
    }
  }
}

UIWeb/Components/PostSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Service.UnitOfWork;

namespace UIWeb.Components
{
  public class PostSummaryViewComponent : ViewComponent
  {
    // DI
    private readonly IServiceManager _manager;

    // Constructor
    public PostSummaryViewComponent(IServiceManager manager)
    {
      _manager = manager;
    }

    // ViewComponent
    public string Invoke() // Gönderi sayısı döner.
    {
      return _manager.PostService.GetAllPosts(false).Count().ToString();
    }
  }
}

UIWeb/Controllers/PostController.cs
using System.Security.Claims;
using Core.Dtos;
using Core.Models;
using Core.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Service.UnitOfWork;
using UIWeb.Models;

namespace UIWeb.Controllers
{
  public class PostController : Controller
  {
    //Dependency Injection
    private readonly IServiceManager _manager;

    // Constructor
    public PostController(IServiceManager manager)
    {
      _manager = manager;
    }

    // SelectList
    private SelectList GetCategories()
    {
      return new SelectList(_manager.CategoryService.GetAllCategories(false), "Id", "Name", "1");
    }

    // Views
    public IActionResult Index(PostRequestParameters p)
    {
      var posts = _manager.PostService.GetAllPostsWithDetails(p).OrderByDescending(p => p.CreatedAt);
      var pagination = new Pagination()
      {
        CurrentPage = p.PageNumber,
        ItemsPerPage = p.PageSize,
        TotalItems = _manager.PostService.GetAllPosts(false).Count()
      };
      return View(new PostListViewModel()
      {
        Posts = posts,
        Pagination = pagination
      });
    }

    public IActionResult Get([FromRoute(Name = "id")] int id)
    {
      var model = _manager.PostService.GetOnePost(id, false);
      return View(model);
    }

    public IActionResult Create()
    {
      ViewBag.Categories = GetCategories();
      return View();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] PostDtoForCreation postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();
      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);
        postDto.UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

        _manager.PostService.CreateOnePost(postDto);
        TempData["success"] = $"{postDto.Title} oluşturuldu.";
        return RedirectToAction("Index");
      }
      return View();
    }

    public IActionResult Update([FromRoute(Name = "id")] int id)
    {
      ViewBag.Categories = GetCategories();
      var model = _manager.PostService.GetOnePostForUpdate(id, false);
      return View(model);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update([FromForm] PostDtoForUpdate postDto, IFormFile file)
    {
      ViewBag.Categories = GetCategories();

      if (ModelState.IsValid)
      {
        //dosyalama işlemleri
        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
        using (var stream = new FileStream(path, FileMode.Create))
        {
          await file.CopyToAsync(stream);
        }
        postDto.ImageUrl = String.Concat("/images/", file.FileName);

        _manager.PostService.UpdateOnePost(postDto);
        return RedirectToAction("Index");
      }
      return View(postDto);
    }

    public IActionResult Delete(int id)
    {
      _manager.PostService.DeleteOnePost(id);
      TempData["danger"] = "Gönderi silindi!";
      return RedirectToAction("Index");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddComment([FromForm] CommentDto commentDto)
    {
      if (ModelState.IsValid)
      {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        commentDto.UserId = userId;
        _manager.CommentService.CreateComment(commentDto);
        return RedirectToAction("Get", new { id = commentDto.PostId });
      }
      return View("Get", _manager.PostService.GetOnePost(commentDto.PostId, false));
    }
    [HttpPost("Post/{postId}/RemoveComment")]
    [ValidateAntiForgeryToken]
    public IActionResult RemoveComment([FromRoute] int postId, [FromForm] int commentId)
    {
      _manager.CommentService.RemoveComment(commentId);
      return RedirectToAction("Get", new { id = postId });
    }

    [HttpPost("Post/{postId}/ToggleLike")]
    [ValidateAntiForgeryToken]
    public IActionResult ToggleLike([FromRoute] int postId)
    {
      var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
      if (string.IsNullOrEmpty(userId))
        return Unauthorized();
      _manager.LikeService.ToggleLike(postId, userId);
      return RedirectToAction("Get", new { id = postId });
    }
  }
}

UIWeb/Areas/Admin/Views/Dashboard/Index.cshtml
<h1>
  <Dashboard Index>
</h1>
<div>
  <partial name="_Cards" />
</div>

UIWeb/Areas/Admin/Views/Dashboard/_Cards.cshtml
<div class="row g-3 py-5">
  <div class="col-lg-6">
    <div class="card bg-success text-white p-2" style="width: 18rem;">
      <div class="card-body text-center">
        <h6 class="card-subtitle mb-2">Toplam</h6>
        <h5 class="card-title"><b>Üyeler</b></h5>
        <h5 class="text-center display-5">@await Component.InvokeAsync("MemberSummary")</h5>
        <a asp-controller="User" asp-action="Index" class="card-link text-white">Üyeler</a>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card bg-danger text-white p-2" style="width: 18rem;">
      <div class="card-body text-center">
        <h6 class="card-subtitle mb-2">Toplam</h6>
        <h5 class="card-title"><b>Gönderiler</b></h5>
        <h5 class="text-center display-5">@await Component.InvokeAsync("PostSummary")</h5>
        <a asp-controller="Post" asp-action="Index" class="card-link text-white">Gönderiler</a>
        <a asp-area="" asp-controller="Post" asp-action="Index" class="card-link text-white">Sayfada Gör</a>
      </div>
    </div>
  </div>
</div>
<div class="row g-3 py-5">
  <div class="col-lg-6">
    <div class="card bg-info text-white p-2" style="width: 18rem;">
      <div class="card-body text-center">
        <h5 class="card-title"><b>Kaç Yorum Yapıldı?</b></h5>
        <h5 class="text-center display-5">@await Component.InvokeAsync("AllCommentSummary")</h5>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card bg-warning text-white p-2" style="width: 18rem;">
      <div class="card-body text-center">
        <h5 class="card-title"><b>Kaç Beğeni Yapıldı?</b></h5>
        <h5 class="text-center display-5">@await Component.InvokeAsync("AllLikeSummary")</h5>
      </div>
    </div>
  </div>
</div>